/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var problem2 = function() {
  var sum = 0;

  var last = 1;
  var beforeLast = 0;
  var temp;
 
  while(last < 4000000) {
  	if(last % 2 === 0) {
  	  sum += last;
  	}
  	temp = last;
  	last = last + beforeLast;
  	beforeLast = temp;
  }
  return sum;
};